### ISSUE TITLE
Cell config option, only prompt when not defined in ENV

### ISSUE THREAD

**Issue by admc** [stateful/vscode-runme#645] opened 2023-06-30 12:02 UTC
@aluedeke is interested in having a setting where the environment variable behavior is only honored if not already set in the users ENV.

**Comment by sourishkrout** [comment] 2023-06-30 12:53
Duplicate of https://github.com/stateful/vscode-runme/issues/643. We will turn this around fairly quickly.

**Closed by sourishkrout** 2023-06-30 12:53 UTC
Labels: enhancement
