### ISSUE TITLE
Add Runme to recommended extensions options

### ISSUE THREAD

**Issue by degrammer** [stateful/vscode-runme#616] opened 2023-06-15 23:48 UTC
The recommendation dialog to add Runme to recommended extensions should include the following options:
-  Dismiss option per workspace
-  Dismiss option globally

**Comment by sourishkrout** [comment] 2023-06-16 15:33
Duplicate of https://github.com/stateful/vscode-runme/issues/615

**Closed by sourishkrout** 2023-06-16 15:33 UTC
