### ISSUE TITLE
Run All only executes cells when scrolled into view

### ISSUE THREAD

**Issue by degrammer** [stateful/vscode-runme#570] opened 2023-06-01 22:17 UTC
Using the Run-All or Run by category feature only executes cells when visible, the user needs to scroll down in order to start the execution.

Expected Outcome:
Explore if we can scroll each time a cell execution ends and a new one is about to start, scroll into that new cell execution.
 
📹  Demo of the issue:

https://github.com/stateful/vscode-runme/assets/4001529/26decc62-b38c-4f49-a775-2dc55db9e507

**Comment by joseeantonior** [comment] 2023-10-30 22:19
I am unable to reproduce this. Closing, but can reopen if necessary.

**Closed by joseeantonior** 2023-10-30 22:19 UTC
