### ISSUE TITLE
Configuration changes for code cells don't persist

### ISSUE THREAD

**Issue by christian-bromann** [stateful/vscode-runme#188] opened 2023-02-10 17:01 UTC
To reproduce: create a new markdown file and try to modify the configs. It seems that disabling interactive mode doesn't persist, e.g.:

![bug-authoring](https://user-images.githubusercontent.com/731337/218151617-c204e6e1-3e5b-441e-9228-a1c0ae198107.gif)

**Comment by sourishkrout** [comment] 2023-02-10 17:04
When you have a chance, let's take a look please @degrammer.

**Comment by sourishkrout** [comment] 2023-02-10 19:07
Interesting tidbit, I took me a while to reproduce. It only appears to happen when a new code-cell is being added via the in-notebook UX `+ Code`. Having built some of this code, I wouldn't be surprised if it does not have a `uuid` to identify it until it was serialized/deserialized.

**Comment by sourishkrout** [comment] 2023-02-10 19:29
Assigning this back to myself since I think I know how to fix this.

**Closed** 2023-02-14 14:31 UTC
Labels: bug
