### ISSUE TITLE
Introduce e2e test for GitHub integration

### ISSUE THREAD

**Issue by degrammer** [stateful/vscode-runme#749] opened 2023-07-31 17:50 UTC
We need an e2e test suite covering our GitHub integration, ensure  it renders properly in a notebook.

**Comment by christian-bromann** [comment] 2023-07-31 17:51
Duplicate of #748 ?

**Comment by sourishkrout** [comment] 2023-07-31 17:51
Yep, duplicate of https://github.com/stateful/vscode-runme/issues/748

**Closed by sourishkrout** 2023-07-31 17:51 UTC
